### ISSUE TITLE
[FROMEMAIL] is not replaced when used in template

### ISSUE THREAD

**Issue by unixtam** [phpList/phplist3#272]

**Comment by unixtam** [comment]
On second thought, [FROMEMAIL] *is* properly replaced in the footer, and putting [FOOTER] in a template works, so maybe I have been using the template in a way that it's not intended to be used?

**Comment by joshmaines** [comment]
I would assume that [FROMEMAIL] should work anywhere in the email message, too, but most people probably don't even use this placeholder at all. I would like to know where the parsing takes place in the code so I could apply a fix on my own installation, because we might have someone try to use this placeholder sometime, not knowing about this limitation.

**Comment by unixtam** [comment]
Check out the fix referenced above (#273).
