### ISSUE TITLE
A question not and issue: Will asubscribe work with built-in captcha plugin?  

### ISSUE THREAD

**Issue by mrojnetsky** [phpList/phplist3#337]
Hi there,

I didn't try that. But by just thinking about it, it doesn't look like this combination will work. I mean you would have to do other calls (which I don't see and API for) to display and process captcha before posting to asubscribe.

If the above is true, should one just roll it's own captcha integration or the built-in plugin can be leveraged somehow? 

Thanks

**Comment by samtuke** [comment]
@asdr45fsd35fdf Is your goal to add captchas (via the captcha plugin) to the unsubscribe page?

This plugin hook allows you to override the default unsubscribe page: [unsubscribePage()](https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/defaultplugin.php#L1051)

Another way would be to update the unsubscribe page template that is stored in the database (to make it user editable).

From a user perspective, perhaps the best approach would be to extend the captcha plugin to add an option to add captchas to unsubscribe pages (instead of creating a separate plugin).

Does that help?

**Comment by samtuke** [comment]
FYI @bramley

**Comment by bramley** [comment]
@asdr45fsd35fdf If you want to use asubscribe then you need to create your own subscribe form to be included on your web site. Usually those tend to be small so adding captcha might disrupt the layout too much.

If you want captcha to be used then you'll need to look at the phplist subscribe page to copy and possibly modify the chunk of html that deals with captcha. So long as the same fields are submitted then the plugin will validate them.

To ensure that a different captcha is displayed each time there needs to be a random number generated. That is done automatically when the html is generated by the plugin but would need to be done by client side code in your case, see the quick start guide for an example

https://www.phpcaptcha.org/documentation/quickstart-guide/

**Comment by mrojnetsky** [comment]
@samtuke
Sorry, I should have provided more context. I'm using asubscribe (ajax integration). I want captcha on my subscribe page (my html not phpList subscribe page) not the unsubscribe page. This is to prevent bots from spamming me. I saw built-in captcha plugin (that was disabled by default for me as it needs core plugin enabled first I think). I did not see a way how to integrate this captcha plugin into my custom html that uses asubscribe. 

@bramley 
Yes, that what I did. My site is one single html page with custom subscribe form. I don't want the user to leave my page. Thank you for the suggestion I will try to piggyback on what "phplist subscribe page" does when captcha is enabled. 
I suspected that the plugin might not work with asubscribe out-of-the-box. Thank you for the link. I will investigate this.

The issue is closed as far as I'm concerned.
