### ISSUE TITLE
List-ID?

### ISSUE THREAD

**Issue by Maasik** [phpList/phplist3#459]
Is the list-ID support planned? 
https://tools.ietf.org/html/rfc2919
Some services (https://yandex.com/support/postoffice/advices.html) use it for statistics.

**Comment by samtuke** [comment]
Thanks for the suggestion - no it's not currently planned, though it could be easily added. 

Isn't that header intended for use with many-to-many mailing list systems like mailman, rather than for one-to-many newsletter and marketing systems like phpList?

What would be the benefit for phpList users?

**Comment by samtuke** [comment]
@Maasik We're still keen to hear you're views on this

**Comment by marianaballa** [comment]
This issue seems to have been abandoned in a long time and there is no progress. For future proposals/questions I would recommend the [community forum](https://discuss.phplist.org/) or [Mantis, the phpList bug tracker](https://mantis.phplist.org/my_view_page.php).

Closing this.
