### ISSUE TITLE
Error when install PhPList

### ISSUE THREAD

**Issue by Hartick** [phpList/phplist3#591]
Hi!
I'm trying to install PHPlist with commandline using a command /usr/bin/phplist -pinitialise, but it don't work. I got this command on Docker version of phplist.
However, the wizard installation /admin don't start.

**Comment by marianaballa** [comment]
Hello @Hartick! Thanks for submitting a new issue. https://discuss.phplist.org/ is a better place for your question above. There are hundreds of community members who can help there. Also, you can use the search button there because someone might have had the same problem in the past.  

Cheers
Mariana

**Comment by marianaballa** [comment]
Closing this issue.
