### ISSUE TITLE
Discrepancy in placeholders

### ISSUE THREAD

**Issue by onavsaber** [phpList/phplist3#694]
When creating a new campaign, the placeholder for "First Name" has different formatting under the help sections. 
The one mentioned earlier is without space: "Dear [FirstName%%friend]". But the true usage seems to be "First Name".

![image](https://user-images.githubusercontent.com/59264927/89441748-3ca4b880-d713-11ea-9821-fa1413830843.png)

**Comment by michield** [comment]
That is because the top part of the explanation is "generic" and only the part that lists your attributes is based on the attributes you have defined. So, the "FIRSTNAME" is an example when you have an attribute called "FirstName" (without a space). 

I guess that may be slightly confusing, feel free to PR a change to make it more clear.
