### ISSUE TITLE
only super admins should be able to change settings and plugins

### ISSUE THREAD

**Issue by rasos** [phpList/phplist3#798]
Currently any admin can change important settings such as domain, header or footer. We think this should be only editable by super admins and not by normal admins, who manage lists.

**Comment by bramley** [comment]
I think that access to the Settings page and other items on the Config menu are controlled by giving the admin Settings privilege
![image](https://user-images.githubusercontent.com/3147688/133045293-f9968a59-8190-40de-959d-0cb2473688ec.png)

But I think that something may have been changed recently, because an ordinary admin now can see all other admins. I am fairly sure that did not used to be the case. An ordinary admin used to be able to see only their own details, not any others.

**Comment by bramley** [comment]
> because an ordinary admin now can see all other admins. 

That appears to have always been the case. An ordinary admin cannot delete other admins, which is still true.

**Comment by michield** [comment]
I've created a login on https://demo.phplist.org/lists/admin/

login: admin2
password: testing1
(I'm not sure how long these credentials will work for, at some point that will be wiped probably)

This is not a superuser and does not have the "Change Settings" ability.

What is it the admin can do that you think it should not be allowed to do?

**Comment by rasos** [comment]
Okay, I finally found the config settings checkbox which can be assigned to any admin. Unchecking that prohibits changes. Now we can give away a demo account without making big harm (limiting how many mails can be sent per admin would be nice, though ...)
